services:
  - type: web
    name: sneakerhub
    runtime: python
    pythonVersion: 3.13
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: >
      gunicorn sneakerhub.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 60
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
      - key: SECRET_KEY
        scope: runtime
      - key: DJANGO_DEBUG
        value: 'False'
